-- Phase 4 telemetry: log every game so we can answer "how many games have
-- been played." The PartyKit server posts a row when a game starts and an
-- update when it ends. Schema is deliberately minimal — add columns only as
-- new questions actually come up.

CREATE TABLE games (
  id TEXT PRIMARY KEY,                  -- random UUID generated by the server
  room_code TEXT NOT NULL,              -- the 4-letter lobby code
  started_at INTEGER NOT NULL,          -- ms epoch when the first round began
  ended_at INTEGER,                     -- ms epoch when endGame ran; null while live
  player_count INTEGER NOT NULL,        -- count at start (mid-game joiners not tracked here)
  total_turns INTEGER,                  -- hadTurn count at end; null while live
  category_label TEXT NOT NULL,         -- 'movies', 'animals', etc, OR the custom deck name
  is_custom_deck INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_games_started_at ON games(started_at);
