export type Category = 'movies' | 'animals' | 'famous-people' | 'actions';

export const WORDS: Record<Category, string[]> = {
  movies: [
    'Titanic',
    'Avatar',
    'Star Wars',
    'The Lion King',
    'Jurassic Park',
    'Finding Nemo',
    'Toy Story',
    'The Matrix',
    'Harry Potter',
    'Frozen',
    'Shrek',
    'Spider-Man',
    'Batman',
    'The Godfather',
    'Jaws',
    'E.T.',
    'Indiana Jones',
    'Back to the Future',
    'Ghostbusters',
    'The Terminator',
    'Rocky',
    'Grease',
    'The Wizard of Oz',
    'Forrest Gump',
    'The Avengers',
    'Iron Man',
    'Transformers',
    'Pirates of the Caribbean',
    'The Incredibles',
    'Up',
    'Inside Out',
    'Moana',
    'Coco',
    'Ratatouille',
    'WALL-E',
    'Monsters Inc',
    'The Hunger Games',
    'Twilight',
    'Mission Impossible',
    'James Bond',
    'Fast and Furious',
    'Home Alone',
    'Elf',
    'The Grinch',
    'Mean Girls',
    'Legally Blonde',
    'The Notebook',
    'Titanic',
    'Pretty Woman',
    'Dirty Dancing'
  ],
  animals: [
    'Elephant',
    'Giraffe',
    'Penguin',
    'Kangaroo',
    'Dolphin',
    'Octopus',
    'Butterfly',
    'Crocodile',
    'Flamingo',
    'Peacock',
    'Gorilla',
    'Chimpanzee',
    'Rhinoceros',
    'Hippopotamus',
    'Zebra',
    'Tiger',
    'Lion',
    'Cheetah',
    'Leopard',
    'Panther',
    'Wolf',
    'Fox',
    'Bear',
    'Koala',
    'Panda',
    'Sloth',
    'Armadillo',
    'Porcupine',
    'Hedgehog',
    'Squirrel',
    'Rabbit',
    'Hamster',
    'Guinea Pig',
    'Parrot',
    'Eagle',
    'Owl',
    'Hummingbird',
    'Pelican',
    'Shark',
    'Whale',
    'Jellyfish',
    'Seahorse',
    'Starfish',
    'Crab',
    'Lobster',
    'Snake',
    'Lizard',
    'Chameleon',
    'Turtle',
    'Frog'
  ],
  'famous-people': [
    'Taylor Swift',
    'Beyonce',
    'Michael Jackson',
    'Elvis Presley',
    'Madonna',
    'Lady Gaga',
    'Adele',
    'Drake',
    'Kanye West',
    'Rihanna',
    'Tom Hanks',
    'Leonardo DiCaprio',
    'Brad Pitt',
    'Angelina Jolie',
    'Jennifer Aniston',
    'Dwayne Johnson',
    'Will Smith',
    'Morgan Freeman',
    'Meryl Streep',
    'Julia Roberts',
    'Barack Obama',
    'Albert Einstein',
    'Oprah Winfrey',
    'Elon Musk',
    'Bill Gates',
    'Steve Jobs',
    'Mark Zuckerberg',
    'Jeff Bezos',
    'Michael Jordan',
    'LeBron James',
    'Serena Williams',
    'Tiger Woods',
    'Cristiano Ronaldo',
    'Lionel Messi',
    'Usain Bolt',
    'Muhammad Ali',
    'Princess Diana',
    'Queen Elizabeth',
    'Marilyn Monroe',
    'Audrey Hepburn',
    'Cleopatra',
    'Abraham Lincoln',
    'George Washington',
    'Martin Luther King Jr',
    'Gandhi',
    'Nelson Mandela',
    'Shakespeare',
    'Picasso',
    'Walt Disney',
    'Mr Beast'
  ],
  actions: [
    'Dancing',
    'Swimming',
    'Running',
    'Jumping',
    'Climbing',
    'Flying',
    'Driving',
    'Cooking',
    'Eating',
    'Sleeping',
    'Snoring',
    'Laughing',
    'Crying',
    'Sneezing',
    'Coughing',
    'Yawning',
    'Stretching',
    'Exercising',
    'Yoga',
    'Meditating',
    'Singing',
    'Playing Guitar',
    'Playing Piano',
    'Painting',
    'Drawing',
    'Sculpting',
    'Knitting',
    'Sewing',
    'Fishing',
    'Hunting',
    'Camping',
    'Hiking',
    'Skiing',
    'Snowboarding',
    'Surfing',
    'Skateboarding',
    'Rollerblading',
    'Bowling',
    'Golfing',
    'Boxing',
    'Wrestling',
    'Karate',
    'Juggling',
    'Magic Trick',
    'Tightrope Walking',
    'Bungee Jumping',
    'Skydiving',
    'Taking Selfie',
    'Video Gaming',
    'Texting'
  ]
};

export function getShuffledWords(category: Category): string[] {
  const words = [...WORDS[category]];
  // Fisher-Yates shuffle
  for (let i = words.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [words[i], words[j]] = [words[j], words[i]];
  }
  return words;
}
