export type Category = 'movies' | 'animals' | 'famous-people' | 'actions';

export const WORDS: Record<Category, string[]> = {
  movies: [
    'Titanic',
    'Avatar',
    'Star Wars',
    'The Lion King',
    'Jurassic Park',
    'Finding Nemo',
    'Toy Story',
    'The Matrix',
    'Harry Potter',
    'Frozen',
    'Shrek',
    'Spider-Man',
    'Batman',
    'The Godfather',
    'Jaws',
    'E.T.',
    'Indiana Jones',
    'Back to the Future',
    'Ghostbusters',
    'The Terminator',
    'Rocky',
    'Grease',
    'The Wizard of Oz',
    'Forrest Gump',
    'The Avengers',
    'Iron Man',
    'Transformers',
    'Pirates of the Caribbean',
    'The Incredibles',
    'Up',
    'Inside Out',
    'Moana',
    'Coco',
    'Ratatouille',
    'WALL-E',
    'Monsters Inc',
    'The Hunger Games',
    'Twilight',
    'Mission Impossible',
    'James Bond',
    'Fast and Furious',
    'Home Alone',
    'Elf',
    'The Grinch',
    'Mean Girls',
    'Legally Blonde',
    'The Notebook',
    'Pretty Woman',
    'Dirty Dancing',
    'Aladdin',
    'Beauty and the Beast',
    'The Little Mermaid',
    'Cinderella',
    'Snow White',
    'Sleeping Beauty',
    'Peter Pan',
    'Bambi',
    'Dumbo',
    'Mulan',
    'Tangled',
    'Brave',
    'Zootopia',
    'The Princess Bride',
    'Willy Wonka',
    'Mary Poppins',
    'The Sound of Music',
    'Singin in the Rain',
    'Casablanca',
    'Gone with the Wind',
    'Psycho',
    'The Shining',
    'Scream',
    'Halloween',
    'A Nightmare on Elm Street',
    'It',
    'The Exorcist',
    'Alien',
    'Predator',
    'The Dark Knight',
    'Superman',
    'Wonder Woman',
    'Black Panther',
    'Guardians of the Galaxy',
    'Deadpool',
    'X-Men',
    'Captain America',
    'Thor',
    'Doctor Strange',
    'Star Trek',
    'The Lord of the Rings',
    'The Hobbit',
    'Dune',
    'Gladiator',
    'Braveheart',
    'Top Gun',
    'Pulp Fiction',
    'The Shawshank Redemption',
    'Inception',
    'Minions',
    'Despicable Me'
  ],
  animals: [
    'Elephant',
    'Giraffe',
    'Penguin',
    'Kangaroo',
    'Dolphin',
    'Octopus',
    'Butterfly',
    'Crocodile',
    'Flamingo',
    'Peacock',
    'Gorilla',
    'Chimpanzee',
    'Rhinoceros',
    'Hippopotamus',
    'Zebra',
    'Tiger',
    'Lion',
    'Cheetah',
    'Leopard',
    'Panther',
    'Wolf',
    'Fox',
    'Bear',
    'Koala',
    'Panda',
    'Sloth',
    'Armadillo',
    'Porcupine',
    'Hedgehog',
    'Squirrel',
    'Rabbit',
    'Hamster',
    'Guinea Pig',
    'Parrot',
    'Eagle',
    'Owl',
    'Hummingbird',
    'Pelican',
    'Shark',
    'Whale',
    'Jellyfish',
    'Seahorse',
    'Starfish',
    'Crab',
    'Lobster',
    'Snake',
    'Lizard',
    'Chameleon',
    'Turtle',
    'Frog',
    'Monkey',
    'Baboon',
    'Orangutan',
    'Lemur',
    'Raccoon',
    'Skunk',
    'Beaver',
    'Otter',
    'Platypus',
    'Wombat',
    'Wallaby',
    'Tasmanian Devil',
    'Meerkat',
    'Mongoose',
    'Buffalo',
    'Bison',
    'Moose',
    'Elk',
    'Deer',
    'Reindeer',
    'Camel',
    'Llama',
    'Alpaca',
    'Horse',
    'Donkey',
    'Cow',
    'Pig',
    'Sheep',
    'Goat',
    'Chicken',
    'Rooster',
    'Duck',
    'Goose',
    'Swan',
    'Turkey',
    'Ostrich',
    'Emu',
    'Bat',
    'Mouse',
    'Rat',
    'Beetle',
    'Ladybug',
    'Grasshopper',
    'Cricket',
    'Ant',
    'Bee',
    'Wasp',
    'Spider',
    'Scorpion',
    'Snail'
  ],
  'famous-people': [
    'Taylor Swift',
    'Beyonce',
    'Michael Jackson',
    'Elvis Presley',
    'Madonna',
    'Lady Gaga',
    'Adele',
    'Drake',
    'Kanye West',
    'Rihanna',
    'Tom Hanks',
    'Leonardo DiCaprio',
    'Brad Pitt',
    'Angelina Jolie',
    'Jennifer Aniston',
    'Dwayne Johnson',
    'Will Smith',
    'Morgan Freeman',
    'Meryl Streep',
    'Julia Roberts',
    'Barack Obama',
    'Albert Einstein',
    'Oprah Winfrey',
    'Elon Musk',
    'Bill Gates',
    'Steve Jobs',
    'Mark Zuckerberg',
    'Jeff Bezos',
    'Michael Jordan',
    'LeBron James',
    'Serena Williams',
    'Tiger Woods',
    'Cristiano Ronaldo',
    'Lionel Messi',
    'Usain Bolt',
    'Muhammad Ali',
    'Princess Diana',
    'Queen Elizabeth',
    'Marilyn Monroe',
    'Audrey Hepburn',
    'Cleopatra',
    'Abraham Lincoln',
    'George Washington',
    'Martin Luther King Jr',
    'Gandhi',
    'Nelson Mandela',
    'Shakespeare',
    'Picasso',
    'Walt Disney',
    'Mr Beast',
    'Justin Bieber',
    'Ariana Grande',
    'Katy Perry',
    'Bruno Mars',
    'Ed Sheeran',
    'Billie Eilish',
    'The Beatles',
    'Elton John',
    'Freddie Mercury',
    'Bob Dylan',
    'Whitney Houston',
    'Prince',
    'John Lennon',
    'Paul McCartney',
    'Tupac',
    'Eminem',
    'Snoop Dogg',
    'Jay-Z',
    'Robert Downey Jr',
    'Chris Evans',
    'Chris Hemsworth',
    'Scarlett Johansson',
    'Jennifer Lawrence',
    'Emma Stone',
    'Ryan Reynolds',
    'Ryan Gosling',
    'Keanu Reeves',
    'Johnny Depp',
    'Robert De Niro',
    'Al Pacino',
    'Tom Cruise',
    'Denzel Washington',
    'Arnold Schwarzenegger',
    'Samuel L Jackson',
    'Betty White',
    'Robin Williams',
    'Steven Spielberg',
    'Stan Lee',
    'JK Rowling',
    'Stephen King',
    'Vincent van Gogh',
    'Leonardo da Vinci',
    'Michelangelo',
    'Mozart',
    'Beethoven',
    'Isaac Newton',
    'Charles Darwin',
    'Marie Curie',
    'Nikola Tesla',
    'Thomas Edison'
  ],
  actions: [
    'Dancing',
    'Swimming',
    'Running',
    'Jumping',
    'Climbing',
    'Flying',
    'Driving',
    'Cooking',
    'Eating',
    'Sleeping',
    'Snoring',
    'Laughing',
    'Crying',
    'Sneezing',
    'Coughing',
    'Yawning',
    'Stretching',
    'Exercising',
    'Yoga',
    'Meditating',
    'Singing',
    'Playing Guitar',
    'Playing Piano',
    'Painting',
    'Drawing',
    'Sculpting',
    'Knitting',
    'Sewing',
    'Fishing',
    'Hunting',
    'Camping',
    'Hiking',
    'Skiing',
    'Snowboarding',
    'Surfing',
    'Skateboarding',
    'Rollerblading',
    'Bowling',
    'Golfing',
    'Boxing',
    'Wrestling',
    'Karate',
    'Juggling',
    'Magic Trick',
    'Tightrope Walking',
    'Bungee Jumping',
    'Skydiving',
    'Taking Selfie',
    'Video Gaming',
    'Texting',
    'Walking',
    'Skipping',
    'Tiptoeing',
    'Sprinting',
    'Crawling',
    'Limping',
    'Marching',
    'Tap Dancing',
    'Ballet',
    'Waltzing',
    'Breakdancing',
    'Salsa',
    'Hip Hop',
    'Cheerleading',
    'Clapping',
    'Waving',
    'Pointing',
    'Shaking Hands',
    'Hugging',
    'Kissing',
    'Winking',
    'Smiling',
    'Frowning',
    'Blinking',
    'Whistling',
    'Humming',
    'Rapping',
    'Beatboxing',
    'Drumming',
    'Conducting',
    'Typing',
    'Reading',
    'Writing',
    'Washing Dishes',
    'Scuba Diving',
    'Sailing',
    'Rowing',
    'Kayaking',
    'Canoeing',
    'Horseback Riding',
    'Rock Climbing',
    'Parkour',
    'Playing Chess',
    'Playing Cards',
    'Gambling',
    'Shopping',
    'Gardening',
    'Mowing Lawn',
    'Raking Leaves',
    'Vacuuming'
  ]
};

export function getShuffledWords(category: Category): string[] {
  const words = [...WORDS[category]];
  // Fisher-Yates shuffle
  for (let i = words.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [words[i], words[j]] = [words[j], words[i]];
  }
  return words;
}
